import Head from "next/head";
import Image from "next/image";

import { Open_Sans } from "next/font/google";
import HomePage from "@/views/HomePage";

const openSans = Open_Sans({
  subsets: ["latin"],
  variable: "--open-sans",
});

export default function Home() {
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={openSans.variable}>
        <HomePage />
      </div>
    </>
  );
}
